/** Lista de áreas municipales (combustible, vehículos, etc.) */
export const AREAS = [
  'Bromatología',
  'Cementerio',
  'Centros de Salud',
  'Corralón',
  'Corralón Sur',
  'Dependencias policiales',
  'Dir. Coordinación',
  'Dirección de Deportes',
  'Dirección de Obras Particulares',
  'Inspección General',
  'Intendente Municipal',
  'Juzgado de Faltas',
  'Medio Ambiente',
  'Obras Públicas',
  'Obras Sanitarias',
  'PUM',
  'Relaciones con la comunidad',
  'Sec. de Desarrollo de la Comunidad',
  'Secretaría de Hacienda',
  'Secretaría de Obras',
  'Secretaría de Planeamiento',
  'Secretaría de Salud',
  'Secretaría de Seguridad',
  'Seguridad en Playa',
  'Tránsito',
  'Transporte',
  'Turismo',
  'Verificación en Playa',
  'Zoonosis',
]

export default AREAS
