const areas = [
  "Intendente Municipal",
  "Comisaría primera",
  "Comisaría Segunda",
  "Comisaría tercera",
  "Comisaría cuarta",
  "Policía científica",
  "DDI",
  "Policía vial",
  "Alcoholemia",
  "Comisaría de la mujer",
  "Comisaría comunal",
  "Caballería",
  "Caballería villa gesell",
  "Caballería mar azul",
  "GAD",
  "DDA",
  "Inteligencia",
  "Guardia urbana",
  "PUM",
  "Secretaría de Salud",
  "Secretaría de Hacienda",
  "Secretaría de Obras",
  "Dirección de Deportes",
  "Verificación en Playa",
  "Juzgado de Faltas",
  "Inspección General",
  "Dir. Coordinación",
  "Cementerio",
  "Dirección de Obras Particulares",
  "Seguridad en Playa",
  "Medio Ambiente",
  "Tránsito",
  "Turismo",
  "Sec. de Desarrollo de la Comunidad",
  "Secretaría de Seguridad",
  "Corralón",
  "Corralón Sur",
  "Obras Sanitarias",
  "Obras Públicas",
  "Transporte",
  "Secretaría de Planeamiento"
];

export default areas;
