const rubros = [
  {
    id: 1,
    nombre: 'Carnicerías',
    descripcion: 'Establecimiento comercial dedicado pre eminentemente al fraccionamiento de cortes bovinos, ovinos, porcinos y caprinos en general, así como a sus menudencias y embutidos y productos de granja.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 Inc. d, f, g y h", "Art 8"],
    links: [],
    pom: "https://drive.google.com/file/d/1TVOiJ8EwxOOp9y326iG05yFmasKsWYuF/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 2,
    nombre: 'Pescadería',
    descripcion: 'Establecimientos dedicados a la venta de productos de mar y agua. Podrán vender frutos de mar frescos, conservado, congelado o en conserva envasados.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 Inc. d, f, g y h"],
    links: [],
    pom: "https://drive.google.com/file/d/1TVOiJ8EwxOOp9y326iG05yFmasKsWYuF/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 3,
    nombre: 'Verdulería',
    descripcion: 'Establecimiento dedicado pre eminentemente a la venta de frutas, hortalizas, tubérculos y/o verduras sueltas o envasados, frutas secas, carbón embolsado en material ecológico en estanterías o lugar separado. Anexo Compatible: venta de jugos y vinos.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 Inc. d, f y h"],
    links: [],
    pom: "https://drive.google.com/file/d/1TVOiJ8EwxOOp9y326iG05yFmasKsWYuF/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 4,
    nombre: 'Fiambrería',
    descripcion: 'Establecimiento dedicado preeminentemente a la venta de fiambres preelaborados y quesos. Podrán vender fiambres envasados, embutidos, quesos, lácteos, bebidas y productos envasados.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 Inc. d, f y h"],
    links: [],
    pom: "https://drive.google.com/file/d/1TVOiJ8EwxOOp9y326iG05yFmasKsWYuF/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 5,
    nombre: 'Panadería, Repostería y/o Pastelería',
    descripcion: 'Local destinado a la venta de pan, masas finas, con factibilidad de consumo en el lugar, sin fabricación. Anexo compatible: bebidas.',
    requisitos: ["Art.6"],
    especiales: ["Solo venta: Art 7 Inc. d, y f", "Consumición en el lugar: Art 7 Inc. a, c, d, f y h"],
    links: [],
    pom: "https://drive.google.com/file/d/1TVOiJ8EwxOOp9y326iG05yFmasKsWYuF/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 6,
    nombre: 'Venta de Productos de Granja',
    descripcion: 'Local destinado a la venta minorista de carnes caprinas, conejos y aves y sus derivados.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 Inc. d, f, g y h"],
    links: [],
    pom: "https://drive.google.com/file/d/1TVOiJ8EwxOOp9y326iG05yFmasKsWYuF/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 7,
    nombre: 'Despensa',
    descripcion: 'Local para la venta minorista simultánea, dividido en secciones comercialmente independientes, de sustancias alimenticias en general, bebidas envasadas, tocador, bazar y limpieza. Pudiendo tener como anexo compatible los usos de venta de golosinas y despacho de pan y fiambrería. De superficie máxima de exposición y venta 100 m2.',
    requisitos: ["Art.6"],
    especiales: ["Mesadas y Piletas: Art 7 Inc. d, f y h"],
    links: [],
    pom: "https://drive.google.com/file/d/18p1EpdGflSKAgkxxb2CO1L0-tXJeQVXk/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 8,
    nombre: 'Proveeduría',
    descripcion: 'Local para la venta minorista simultánea, dividido en secciones comercialmente independientes, de sustancias alimenticias en general, bebidas envasadas, tocador, bazar y limpieza. Pudiendo tener como anexo compatible los usos de venta de golosinas y despacho de pan. De superficie máxima de exposición y venta 300 m2.',
    requisitos: ["Art.6"],
    especiales: ["Mesadas y Piletas: Art 7 Inc. d, f, g y h"],
    links: [],
    pom: "https://drive.google.com/file/d/18p1EpdGflSKAgkxxb2CO1L0-tXJeQVXk/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 9,
    nombre: 'Supermercado',
    descripcion: 'Local para la venta minorista simultánea, dividido en secciones comercialmente independientes, de sustancias alimenticias en general, bebidas envasadas, tocador, bazar y limpieza. Pudiendo tener como anexo compatible los usos de venta de golosinas y despacho de pan. De superficie máxima de exposición y venta 900 m2.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 Inc. b, d, e, f, g, y h"],
    links: [],
    pom: "https://drive.google.com/file/d/1XttXzA9tJBsXWCgj9d2bDDfDclhFLB7k/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 10,
    nombre: 'Dietética/Herboristería/Productos Aptos Celíacos',
    descripcion: 'Local para la venta minorista de productos aptos celiacos y dietéticos, hierbas, productos naturales y desecados. Se podrá comercializar productos congelados y envasados.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 Inc. d, f, y h", "Ordenanza N.º 2927/19"],
    links: ["","https://hcdvillagesell.com.ar/ordenanza-2927-19/"],
    pom: "https://drive.google.com/file/d/1-ZEhskPyxtlVZXMsIuJdGcKIb-YwSr7m/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 11,
    nombre: 'Elaboración y Venta de Alfajores, Chocolates y Dulces',
    descripcion: 'Podrán expender además de los productos mencionados como anexo los siguientes usos compatibles cafetería, venta de licores artesanales y repostería. Puede incluir consumo en el lugar.',
    requisitos: ["Art.6"],
    especiales: [ "Art 7 Inc. d y f (venta)", 
                  "Art 7 Inc. a, b, c, d, f, y h (elaboración y venta)",
                  "Croquis de Instalaciones visado por profesional habilitante, escala 1:50 con el siguiente detalle: a) Planta del local con medidas, ubicación de mesadas, tirajes, fogones, cocinas, freidoras, aberturas, paredes internas, y ventilaciones, depósitos, baños, salón de venta y/o consumición, vestuarios, entrepisos, ubicación de garrafas, etc; b) Detalle en corte transversal piso, cielorraso, alturas de tirajes con indicación de altura a 4 vientos; c) Marcar ubicación los matafuegos, clase y kg.",
                ],
    links: [],
    pom: "https://drive.google.com/file/d/1RVUOCenXpMafGFtjBuunpAQn-LbEJsoH/preview",
    inspeccion: true,
    croquis: true,
  },
  {
    id: 12,
    nombre: 'Elaboración y Venta de Bebidas Alcohólicas Artesanales',
    descripcion: 'Establecimiento destinado a la elaboración y venta de bebidas alcohólicas artesanales como vino, cerveza o licores. Sin consumo en el lugar.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 Inc. b, d, f, y h (Ord 1958/04)", "Ordenanza N.º 2752/17"],
    links: ["", "https://hcdvillagesell.com.ar/ordenanza-2752-17/"],
    pom: "https://drive.google.com/file/d/10CC3F3skZnpONUy_mLCW-kxpPjJueYTG/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 13,
    nombre: 'Elaboración y Venta de Pan, Repostería y/o Pastelería',
    descripcion: 'Establecimiento destinado a la elaboración y venta de pan y productos de pastelería y reposterías. Puede incluir consumo en el lugar.',
    requisitos: ["Art.6"],
    especiales: ["Venta: Art 7 Inc. d y f", "Elaboración y Venta: Art 7 Inc. a, b, c, d, f, y h",
                  "Croquis de Instalaciones visado por profesional habilitante, escala 1:50 con el siguiente detalle: a) Planta del local con medidas, ubicación de mesadas, tirajes, fogones, cocinas, freidoras, aberturas, paredes internas, y ventilaciones, depósitos, baños, salón de venta y/o consumición, vestuarios, entrepisos, ubicación de garrafas, etc; b) Detalle en corte transversal piso, cielorraso, alturas de tirajes con indicación de altura a 4 vientos; c) Marcar ubicación los matafuegos, clase y kg.",
                ],
    links: [],
    pom: "https://drive.google.com/file/d/1RVUOCenXpMafGFtjBuunpAQn-LbEJsoH/preview",
    inspeccion: true,
    croquis: true,
  },
  {
    id: 14,
    nombre: 'Local de Venta Comidas para Llevar',
    descripcion: 'Establecimientos destinados a la producción, elaboración, exposición y venta de productos comestibles que no podrán ser consumidos en el lugar. Anexo compatible: Rotiserías y Fiambrerías',
    requisitos: ["Art.6"],
    especiales: ["Art 7 Inc. b, d, y f",
    "Croquis de Instalaciones visado por profesional habilitante, escala 1:50 con el siguiente detalle: a) Planta del local con medidas, ubicación de mesadas, tirajes, fogones, cocinas, freidoras, aberturas, paredes internas, y ventilaciones, depósitos, baños, salón de venta y/o consumición, vestuarios, entrepisos, ubicación de garrafas, etc; b) Detalle en corte transversal piso, cielorraso, alturas de tirajes con indicación de altura a 4 vientos; c) Marcar ubicación los matafuegos, clase y kg.",
                ],
    links: [],
    pom: "https://drive.google.com/file/d/1_1tssDmiqtGhm8G5PIUfKKKACF_cfCTC/preview",
    inspeccion: true,
    croquis: true,
  },
  {
    id: 15,
    nombre: 'Local de Venta de Golosinas Envasadas (Kiosco)',
    descripcion: 'Comercio minorista al público, donde se vende golosinas, cigarrillos, bebidas sin alcohol envasadas o enlatadas, y helados envasados al vacío.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 Inc. d, y f."],
    links: [],
    pom: "https://drive.google.com/file/d/1qUAGtyQt7g_IlqDfysSZfGPcuNfo5vcf/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 16,
    nombre: 'Heladería',
    descripcion: 'Establecimiento destinado a la venta de helados con o sin fabricación en el mismo local. Podrán tener sillas y mesas en el local de venta. Pudiendo tener como anexo compatible los usos de venta de chocolates, cafetería y repostería.',
    requisitos: ["Art.6"],
    especiales: ["Elaboración: Art 7 Inc. b, d y f", "Cafetería: Art 7 Inc. a, c, e, y f",
    "Croquis de Instalaciones visado por profesional habilitante, escala 1:50 con el siguiente detalle: a) Planta del local con medidas, ubicación de mesadas, tirajes, fogones, cocinas, freidoras, aberturas, paredes internas, y ventilaciones, depósitos, baños, salón de venta y/o consumición, vestuarios, entrepisos, ubicación de garrafas, etc; b) Detalle en corte transversal piso, cielorraso, alturas de tirajes con indicación de altura a 4 vientos; c) Marcar ubicación los matafuegos, clase y kg.",
                ],
    links: [],
    pom: "https://drive.google.com/file/d/1y1rlAAb04gFCHjf35m65bH7RsNquEQcm/preview",
    inspeccion: true,
    croquis: true,
  },
  {
    id: 17,
    nombre: 'Venta de Artículos Regionales',
    descripcion: 'Local destinado a la venta de productos alimenticios preenvasados y de realización artesanal como mermeladas, licores tabla de fiambres o embutidos. Puede complementar con fiambrería. Sin consumo en el lugar.',
    requisitos: ["Art.6"],
    especiales: ["Mesadas y Piletas: Art 7 Inc. d, f, y h"],
    links: [],
    pom: "https://drive.google.com/file/d/1RVUOCenXpMafGFtjBuunpAQn-LbEJsoH/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 18,
    nombre: 'Tabaquería, Cigarrería',
    descripcion: 'Local donde se efectúa la venta de productos relacionados con el tabaco.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 Inc. d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1RVUOCenXpMafGFtjBuunpAQn-LbEJsoH/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 19,
    nombre: 'Local de Venta de Antigüedades, Objetos de Arte',
    descripcion: 'Locales destinados a la venta de muebles, vajillas, relojes, adornos, cuadros con valor de antigüedad y/o arte.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 Inc. d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1dMmLOarebjC7j2YIvDUHwEJX8ArynUF4/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 20,
    nombre: 'Local de Venta de Artículos Deportivos',
    descripcion: 'Locales destinados a la venta de artículos y vestimenta deportiva, armas y/o cuchillos de carácter deportivo.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 Inc. d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1PxhmBiNqJGdCU7Dj6eOaygOwSJcKknIi/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 21,
    nombre: 'Vivero',
    descripcion: 'Establecimiento destinado a la venta de flores, semillas, árboles y arbustos, plantas en general. Incluye artículos para el jardín.',
    requisitos: ["Art.6"],
    especiales: ["Art 9 inc. k"],
    links: [],
    pom: "https://drive.google.com/file/d/1yJWpuI7SEQu1GnJttNM73ZLHCwCmA80N/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 22,
    nombre: 'Florería',
    descripcion: 'Locales destinados a la venta de flores y regalos anexos.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1yzAAHwbup38lSrFzFu8Z1WL3mtsMHEmf/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 23,
    nombre: 'Local de Venta de Artículos de Decoración',
    descripcion: 'Locales donde se efectúa la venta de cortinas, alfombras, tapices, rieles, telas para tapicería, papeles decorativos, madera, ornamentos de goma, colas y demás accesorios y útiles para la decoración. Comprende el servicio de asesoramiento y colocación.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/14kdBKZXWQYbq285jYRL3TnA9fjC8rPPl/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 24,
    nombre: 'Venta de Artículos para el Hogar',
    descripcion: 'Comercio minorista, sin depósito en el lugar, destinado a la venta de electrodomésticos, muebles y electrónica. Industria blanca.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/14kdBKZXWQYbq285jYRL3TnA9fjC8rPPl/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 25,
    nombre: 'Venta de Muebles',
    descripcion: 'Local destinado a la venta de muebles de madera, mimbre, aceros, plásticos o similar.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/14kdBKZXWQYbq285jYRL3TnA9fjC8rPPl/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 26,
    nombre: 'Bazar/Regalos',
    descripcion: 'Establecimiento dedicado a la venta de artículos de uso doméstico de almacenamiento y conservación doméstica, instrumentos de cocción, limpieza doméstica, regalos para la decoración.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1XOf1CVHaEglFVk5-nbs1HTfIgp8rCNUj/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 27,
    nombre: 'Mercería/Botonería',
    descripcion: 'Comercio minorista donde se venden accesorios para la vestimenta.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1tXseUuSssXgqJpi3q6rCHfd3QN3t7Box/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 28,
    nombre: 'Tienda de Ropa/De Vestir/De Blanco/Zapatería',
    descripcion: 'Comercio minorista destinado a la venta de indumentaria y/o accesorios de la higiene compuestos por fibras textiles vegetales y/o sintéticas y/o de marroquinería y/o cuero.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1PGY9JoTLwY-s1zXPenE1TaxWZKQq-8-2/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 29,
    nombre: 'Artículos de Playa',
    descripcion: 'Comercio minorista donde se venden accesorios y complementos para estadía en la playa. Incluye protecciones solares, flotantes, anteojos, elementos de sombra, sillas, heladeras, etc.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/14uyzgLsVw20vr6mOt5J36MRWesKTvzdd/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 30,
    nombre: 'Santería, Artículos de Culto',
    descripcion: 'Comercio minorista donde se venden productos asociados al culto y/o liturgia.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1kwwhhGPEPTNkPwWhkZENvre03d5jTNBk/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 31,
    nombre: 'Forrajería',
    descripcion: 'Comercio minorista donde se vende alimentos, semillas, venenos, herramientas y todo lo comprendido en el rubro, con acceso al público.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1l50LRS0UAQeHnp-dhAk6xWqK5w_QoOSk/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 32,
    nombre: 'Mascotería',
    descripcion: 'Local donde se efectúa la venta de artículos para mascotas, incluido alimento.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1p6vWKMOlEh6Dti2i-dVntu-y8vFmJBAH/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 33,
    nombre: 'Óptica y Fotografía',
    descripcion: 'Local de venta de productos ópticos, electrónicos, procesos de revelado, enmarcado. Incluye artículos e instrumentos musicales.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f (Ord. 1958/04)","Ordenanza 1308/95"],
    links: ["","https://hcdvillagesell.com.ar/1308-95-sobre-opticas-habilitadas/"],
    pom: "https://drive.google.com/file/d/1PGY9JoTLwY-s1zXPenE1TaxWZKQq-8-2/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 34,
    nombre: 'Joyería y/o Relojería',
    descripcion: 'Establecimiento dedicado a la venta y/o reparación de joyas y relojes, incluye enmarcados, grabados, encadenados y metalizados.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1PGY9JoTLwY-s1zXPenE1TaxWZKQq-8-2/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 35,
    nombre: 'Farmacia',
    descripcion: 'Comercio minorista donde se venden medicamentos, perfumería y todo lo comprendido.',
    requisitos: ["Art.6"],
    especiales: [],
    links: [],
    pom: "https://drive.google.com/file/d/1p6vWKMOlEh6Dti2i-dVntu-y8vFmJBAH/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 36,
    nombre: 'Perfumería',
    descripcion: 'Comercio minorista donde se venden esencias aromáticas, perfumes o similares.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1p6vWKMOlEh6Dti2i-dVntu-y8vFmJBAH/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 37,
    nombre: 'Artículos de Limpieza/Química',
    descripcion: 'Comercio minorista donde se venden sanitizantes, líquidos envasados destinados a la asepsia, higiene y tocador. Derivados químicos, fraccionados previamente o no.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f","En caso de realizar fraccionamiento deberá indicar medidas del local."],
    links: [],
    pom: "https://drive.google.com/file/d/1Q4bRAF5KGcjaD4-8XTkFjaPd3O06rqnJ/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 38,
    nombre: 'Ortopedia',
    descripcion: 'Locales destinados a la venta de artículos y vinculados a la ortopedia y otros fines médicos.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1yUv7PhfiVLlcPZf51TXm_AOKQ-tvVF19/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 39,
    nombre: 'Local de Venta de Materiales de Construcción p/ terminaciones (exposición y venta)',
    descripcion: 'Local donde se efectúa venta minorista de materiales de construcción con especialidad en revestimientos, sanitarios, carpinterías, electricidad y terminaciones varias, previamente fraccionados, con exhibición de muestras, sin despacho con camiones.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f","Los vehículos afectados a la actividad comercial deben habilitarse en la dirección de tránsito de la municipalidad de Villa Gesell y renovarse según normativa vigente."],
    links: [],
    pom: "https://drive.google.com/file/d/1lITHgFC10gs_kkXWP_vsoVFNkotqzCHz/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 40,
    nombre: 'Pinturería',
    descripcion: 'Local donde se efectúa la venta de artículos de origen químico como pinturas, esmaltes, solvente, pinceles, etc.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f","Los vehículos afectados a la actividad comercial deben habilitarse en la dirección de tránsito de la municipalidad de Villa Gesell y renovarse según normativa vigente."],
    links: [],
    pom: "https://drive.google.com/file/d/1XOf1CVHaEglFVk5-nbs1HTfIgp8rCNUj/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 41,
    nombre: 'Ferretería',
    descripcion: 'Comercio minorista donde se venden herramientas, herrajes, clavos y tornillos, cañerías, repuestos y accesorios en general.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f","Los vehículos afectados a la actividad comercial deben habilitarse en la dirección de tránsito de la municipalidad de Villa Gesell y renovarse según normativa vigente."],
    links: [],
    pom: "https://drive.google.com/file/d/1XttXzA9tJBsXWCgj9d2bDDfDclhFLB7k/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 42,
    nombre: 'Vidriería',
    descripcion: 'Comercio minorista donde se cortan y expenden vidrios y espejos.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f","Los vehículos afectados a la actividad comercial deben habilitarse en la dirección de tránsito de la municipalidad de Villa Gesell y renovarse según normativa vigente."],
    links: [],
    pom: "https://drive.google.com/file/d/1XttXzA9tJBsXWCgj9d2bDDfDclhFLB7k/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 43,
    nombre: 'Cerrajería',
    descripcion: 'Local destinado a la venta y reparación de candados, herrajes, cerraduras, llaves, cajas de seguridad, de tipo mecánico y/o electrónico.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1RP1JUObmKGbxmrzcj08GVAwyROwDipjI/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 44,
    nombre: 'Casa de Iluminación/Productos Eléctricos',
    descripcion: 'Comercio dedicado a la exposición y venta de componentes eléctricos del hogar e iluminación.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f","Los vehículos afectados a la actividad comercial deben habilitarse en la dirección de tránsito de la municipalidad de Villa Gesell y renovarse según normativa vigente."],
    links: [],
    pom: "https://drive.google.com/file/d/1MdsKvkvaPqnwiBmP4WCsA5O6LjfGxZO0/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 45,
    nombre: 'Lavandería',
    descripcion: 'Establecimiento donde se hace recepción y/o lavado y/o limpieza y/o secado y/o planchado de ropa destinado al consumidor final.',
    requisitos: ["Art.6"],
    especiales: ["Con Tintorería: Art 9 inc. f, h", "Deberá presentar Croquis de Instalaciones Sanitarias con ubicación de las lavadoras/secadoras, perforación a napa, tanque de bombeo, instalación de desagüe, en escala 1.50 y firmado por el profesional actuante.", "Lavaderos Industriales deberán presentar Anteproyecto, Plano de Instalación Sanitarias, e Informe de Impacto Ambiental emitido por el Organismo Provincial para el Desarrollo Sostenible (OPDS).", "Los vehículos afectados a la actividad comercial deben habilitarse en la dirección de tránsito de la municipalidad de Villa Gesell y renovarse según normativa vigente."],
    links: [],
    pom: "https://drive.google.com/file/d/1MdsKvkvaPqnwiBmP4WCsA5O6LjfGxZO0/preview",
    inspeccion: true,
    croquis: true,
  },
  {
    id: 46,
    nombre: 'Librería',
    descripcion: 'Establecimiento dedicado a la venta de libros, papeles, insumos de oficina, tintas, sellos, cotillón, envases, envoltorios.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1E4gU05TxtRU_hVPoUyLTcXGbI2BHYrY3/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 47,
    nombre: 'Salón de Estética/Peluquería',
    descripcion: 'Establecimientos donde se preste a las personas servicios de corte y/o lavado y/o peinado del cabello, rasurado de la barba, manicura, aplicaciones de fomentos y masajes faciales y corporales, pedicura, cosmetología y afines (peluquerías).',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d y f", "Art 9 inc. a"],
    links: [],
    pom: "https://drive.google.com/file/d/1p6vWKMOlEh6Dti2i-dVntu-y8vFmJBAH/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 48,
    nombre: 'Bicicleterías',
    descripcion: 'Local destinado a la venta de bicicletas, triciclos y accesorios vinculados.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d y f", "En caso de “alquiler” deberá consultarse a deptocomercio@gesell.gob.ar"],
    links: [],
    pom: "https://drive.google.com/file/d/1Q4bRAF5KGcjaD4-8XTkFjaPd3O06rqnJ/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 49,
    nombre: 'Disquerías, Audio',
    descripcion: 'Local destinado a la venta de grabaciones musicales, bajo cualquier forma, incluye instrumentos musicales. Grabaciones de video.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1p6vWKMOlEh6Dti2i-dVntu-y8vFmJBAH/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 50,
    nombre: 'Computación',
    descripcion: 'Local destinado a la venta de insumos y componentes de la industria de la información. Equipos, papeles, accesorios, repuestos, grabaciones y programas, etc.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1E4gU05TxtRU_hVPoUyLTcXGbI2BHYrY3/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 51,
    nombre: 'Productos Artesanales',
    descripcion: 'Local destinado a la venta elementos elaborados bajo técnicas no industriales, sin repetición o cadena de producción. De elaboración manual o individual.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1HgUVMXLKewgxsJ3aNXc-xg0US9LZ7W5V/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 52,
    nombre: 'Repuestos del Automotor',
    descripcion: 'Venta de repuestos para el automotor sin reparación o colocación en el lugar.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1lITHgFC10gs_kkXWP_vsoVFNkotqzCHz/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 53,
    nombre: 'Calesita/Carrusel',
    descripcion: 'Juego mecánico constituido por una plataforma giratoria con asientos inmóviles y móviles, de diversas formas y colores, simultáneos al movimiento de la plataforma. Incluye otros juegos electromecánicos infantiles.',
    requisitos: [],
    especiales: ["Ordenanza 183/83", "Ordenanza 2005/05: Peloteros"],
    links: ["https://hcdvillagesell.com.ar/0183-83-juegos-ferias-infantiles/","https://hcdvillagesell.com.ar/ordenanza-2005-05/"],
    pom: "https://drive.google.com/file/d/1EfjekaGs9nx50RlCb-chPsVeik2BHpMM/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 54,
    nombre: 'Juegos Electrónicos y/o Electromecánicos',
    descripcion: 'Salón de juegos de naturaleza digital y juegos de carácter electromecánico para toda edad.',
    requisitos: [],
    especiales: ["Ordenanza 1362/95: Locales Juegos Electrónicos", "Ordenanza 2005/05: Peloteros"],
    links: ["https://hcdvillagesell.com.ar/1362-95-derogando-ord-n-185-82-y-ord-100592-locales-juegos-electronicos/","https://hcdvillagesell.com.ar/ordenanza-2005-05/"],
    pom: "https://drive.google.com/file/d/1riBniUFV7Q4GvuQWjARY-Pa41t7TFwsp/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 55,
    nombre: 'Comercios Mayoristas en General',
    descripcion: 'Establecimientos comerciales destinados al almacenamiento y/o exposición y/o venta al por mayor con depósitos y/o distribución de productos para atender a la demanda comercial de la cadena de distribución y/o al consumidor final. Incluye establecimientos con áreas de maniobra y equipos de abastecimiento especiales. Incluye en modo complementario venta minorista. Incluye la venta de elementos y/o productos de gran porte y/o volumen, así como elementos que por su explosividad requieren calificación especial.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, f, g, y h", "Deberá consultarse en deptocomercio@gesell.gob.ar"],
    links: [],
    pom: "",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 56,
    nombre: 'Corralones de Materiales',
    descripcion: 'Establecimientos dedicados a la venta de componentes y materiales de construcción, con superficie de acopio cubierta y/o descubierta, con maniobra de camiones en carga y descarga.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, f, g, y h", "Deberá consultarse a deptocomercio@gesell.gob.ar", "Los vehículos afectados a la actividad comercial deben habilitarse en la dirección de tránsito de la municipalidad de Villa Gesell y renovarse según normativa vigente."],
    links: [],
    pom: "https://drive.google.com/file/d/19Ebpi1j4E8WcT98y3PyxofgM3ns9DKHO/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 57,
    nombre: 'Venta de Gas Envasado',
    descripcion: 'Establecimiento destinado a la venta de garrafas y/o combustibles gaseosos.',
    requisitos: [],
    especiales: ["Ordenanza 503/86", "Resolución 136/03 Secretaría de Energía","Los vehículos afectados a la actividad comercial deben habilitarse en la dirección de tránsito de la municipalidad de Villa Gesell y renovarse según normativa vigente.","Deberán verificar distancia mínima a cualquier establecimiento educativo de 100 ms."],
    links: ["https://hcdvillagesell.com.ar/0503-86-instalacion-planta-gas-envasado/","https://www.argentina.gob.ar/normativa/nacional/resoluci%C3%B3n-136-2003-84203"],
    pom: "https://drive.google.com/file/d/19Ebpi1j4E8WcT98y3PyxofgM3ns9DKHO/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 58,
    nombre: 'Venta de Combustibles/Lubricantes',
    descripcion: 'Establecimiento destinado al despacho de combustibles líquidos y aceites. No refiere a Estación de Servicio.',
    requisitos: ["Art.6"],
    especiales: ["Art. 8 (inc. 26) y art. 9 (inc. c) de la Ordenanza 1958/04", "Ordenanza 1218/94", "Resolución 25/00 Secretaria de Energía","Presentación de Certificado de Instalaciones SASH (Líquidos GNC Duales)", "Deberán verificar distancia mínima a cualquier establecimiento educativo de 100 ms."],
    links: ["","https://hcdvillagesell.com.ar/1218-94-autoservicios-en-estacion-de-servicios/","http://mepriv.mecon.gov.ar/Normas/25-00.htm"],
    pom: "https://drive.google.com/file/d/1bOpcWvrTESWdNYAlv8ew_LmtrxTWh79F/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 59,
    nombre: 'Aserraderos',
    descripcion: 'Establecimiento destinado al fraccionamiento y venta de maderas a granel.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultarse en deptocomercio@gesell.gob.ar", "Los vehículos afectados a la actividad comercial deben habilitarse en la dirección de tránsito de la municipalidad de Villa Gesell y renovarse según normativa vigente."],
    links: [],
    pom: "https://drive.google.com/file/d/19Ebpi1j4E8WcT98y3PyxofgM3ns9DKHO/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 60,
    nombre: 'Depósitos Secos',
    descripcion: 'Local o ambiente cubierto y/o descubierto destinado al almacenamiento genérico de mercaderías sin acceso de consumidores. Puede incluir productos de diferente clasificación en el nomenclador. No incluye productos perecederos.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultarse en deptocomercio@gesell.gob.ar", "Los vehículos afectados a la actividad comercial deben habilitarse en la dirección de tránsito de la municipalidad de Villa Gesell y renovarse según normativa vigente."],
    links: [],
    pom: "https://drive.google.com/file/d/11wU6efrfUFqW_bodk087ul_tsB_HoWs7/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 61,
    nombre: 'Depósitos Húmedos y/o Fríos',
    descripcion: 'Local o ambiente cubierto (refrigerado o no) destinado al almacenamiento de alimentos perecederos. No admite el ingreso de público consumidor.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultarse en deptocomercio@gesell.gob.ar", "Los vehículos afectados a la actividad comercial deben habilitarse en la dirección de tránsito de la municipalidad de Villa Gesell y renovarse según normativa vigente."],
    links: [],
    pom: "https://drive.google.com/file/d/19Ebpi1j4E8WcT98y3PyxofgM3ns9DKHO/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 62,
    nombre: 'Distribuidoras de Bebidas',
    descripcion: 'Establecimiento destinado al almacenamiento, distribución y venta de bebidas previamente fraccionadas con elaboración externa.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultarse en deptocomercio@gesell.gob.ar", "Los vehículos afectados a la actividad comercial deben habilitarse en la dirección de tránsito de la municipalidad de Villa Gesell y renovarse según normativa vigente."],
    links: [],
    pom: "https://drive.google.com/file/d/19Ebpi1j4E8WcT98y3PyxofgM3ns9DKHO/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 63,
    nombre: 'Distribuidoras de Alimentos',
    descripcion: 'Establecimiento destinado al almacenamiento, distribución y venta de alimentos previamente fraccionados con elaboración externa.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, f, y g.", "Los vehículos afectados a la actividad comercial deben habilitarse en la dirección de tránsito de la municipalidad de Villa Gesell y renovarse según normativa vigente."],
    links: [],
    pom: "https://drive.google.com/file/d/19Ebpi1j4E8WcT98y3PyxofgM3ns9DKHO/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 64,
    nombre: 'Papeleras',
    descripcion: 'Local destinado a la venta por menor de envases y envoltorios comerciales.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f", "Los vehículos afectados a la actividad comercial deben habilitarse en la dirección de tránsito de la municipalidad de Villa Gesell y renovarse según normativa vigente."],
    links: [],
    pom: "https://drive.google.com/file/d/19Ebpi1j4E8WcT98y3PyxofgM3ns9DKHO/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 65,
    nombre: 'Venta de Vehículos',
    descripcion: 'Establecimiento destinado a la exhibición y venta de vehículos automotores, motocicletas, bicicletas, náutica, agrícola o similar.',
    requisitos: ["Art.6"],
    especiales: ["Uso transitorio en Terrenos Baldíos: Art 9 inc. L"],
    links: [],
    pom: "https://drive.google.com/file/d/1YSF-4xxuwgnQyTNejAxkoRnTAC2iOoJo/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 66,
    nombre: 'Educación Secundaria',
    descripcion: 'Remitirse a la definición establecida por la Ley 26.206.',
    requisitos: [],
    especiales: ["Ley 26.206"],
    links: ["https://www.argentina.gob.ar/sites/default/files/ley-de-educ-nac-58ac89392ea4c.pdf"],
    pom: "https://drive.google.com/file/d/1vANOmB-z1r7J0RGj7r-jpVXRGdoGd0Qk/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 67,
    nombre: 'Educación Superior',
    descripcion: 'Remitirse a la definición establecida por la Ley 26.206.',
    requisitos: [],
    especiales: ["Ley 26.206"],
    links: ["https://www.argentina.gob.ar/sites/default/files/ley-de-educ-nac-58ac89392ea4c.pdf"],
    pom: "https://drive.google.com/file/d/1AqIDsmNh79YJjRe0iBC8YfqMGGTJtOmU/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 68,
    nombre: 'Educación Especial',
    descripcion: 'Remitirse a la definición establecida en Resolución 311/16 del Consejo Federal de Educación.',
    requisitos: [],
    especiales: ["Resolución 311/16 Consejo Federal de Educación"],
    links: ["http://argentina.gob.ar/sites/default/files/res-311-cfe-58add7585fbc4.pdf"],
    pom: "https://drive.google.com/file/d/1AqIDsmNh79YJjRe0iBC8YfqMGGTJtOmU/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 69,
    nombre: 'Instituto de Investigación',
    descripcion: 'Establecimiento donde se realizan estudios de carácter científico y/o técnico con o sin laboratorio (físico, químico, biológico, etc.).',
    requisitos: [],
    especiales: ["Deberá consultar a deptocomercio@gesell.gob.ar"],
    links: [],
    pom: "https://drive.google.com/file/d/1AqIDsmNh79YJjRe0iBC8YfqMGGTJtOmU/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 70,
    nombre: 'Entidad Protegida de Producción y/o Terapéutica',
    descripcion: 'Entidad estatal o privada bajo dependencia de asociaciones con personería jurídica y reconocidas como de bien público, que tenga por finalidad la producción de bienes o servicios, cuya planta esté integrada por trabajadores discapacidad preparados y entrenados para el trabajo, en edad laboral, y afectados de una incapacidad tal que les dificulte obtener y conservar un empleo competitivo, conforme a lo dispuesto por la Ley Nacional N° 26.816, su reglamentación y modificatorias.',
    requisitos: [],
    especiales: ["Ley Nacional N° 26.816"],
    links: ["https://www.argentina.gob.ar/normativa/nacional/decreto-1771-2015-251275"],
    pom: "https://drive.google.com/file/d/1IHCwRHDON8FV-cRH1TyraviiCkDMNZPQ/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 71,
    nombre: 'Laboratorio de Análisis Clínicos',
    descripcion: 'Establecimientos que tienen por finalidad realizar análisis de muestras biológicas. Incluye también establecimientos destinados a la guarda de personas con atención médica especializada.',
    requisitos: [],
    especiales: ["Deberá consultar a deptocomercio@gesell.gob.ar"],
    links: [],
    pom: "https://drive.google.com/file/d/1k-KYmqSb18C6lDA8tSIb3Sj_IoUmKQJN/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 72,
    nombre: 'Residencia (con Internación) - Discapacidad',
    descripcion: 'Establecimiento destinado a cubrir los requerimientos de vivienda de las personas con discapacidad con suficiente y adecuado nivel de auto-valimiento e independencia para abastecer sus necesidades básicas o que requieran un mínimo de acompañamiento para ello.',
    requisitos: [],
    especiales: ["Ordenanza 1648/02", "Ordenanza 1881/02"],
    links: ["https://hcdvillagesell.com.ar/1648-98-pequenos-hogares-de-tercera-edad/","https://hcdvillagesell.com.ar/1881-02-pequenos-hogares-para-la-tercera-edad-ver-ord-n-1648-98-hogar-geriatrico/"],
    pom: "https://drive.google.com/file/d/1fCwVdqURrCs4zkVu3dYa_Wpt_p2B_nUE/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 73,
    nombre: 'Residencia de Salud Mental',
    descripcion: 'Establecimiento de salud/salud mental, destinado a población con padecimiento mental que requiere mayor cuidado y que por su autonomía limitada y/o su condición de vulnerabilidad pisco –social requiere la provisión de cuidados básicos y esenciales y diversos niveles de apoyo, en el marco de un programa de rehabilitación.',
    requisitos: [],
    especiales: ["Ordenanza 1648/98", "Ordenanza 1881/98"],
    links: ["https://hcdvillagesell.com.ar/1648-98-pequenos-hogares-de-tercera-edad/","https://hcdvillagesell.com.ar/1881-02-pequenos-hogares-para-la-tercera-edad-ver-ord-n-1648-98-hogar-geriatrico/"],
    pom: "https://drive.google.com/file/d/1DNm3yXNUgZdHtVQPgbskhQn97-7uVkGk/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 74,
    nombre: 'Residencia para Personas Mayores',
    descripcion: 'Establecimiento privado residencial o no, que tenga como fin brindar servicios de alojamiento, alimentación, higiene, recreación y/o atención médica y psicológica no sanatorial a personas mayores de sesenta (60) años, en forma permanente o transitoria, a título oneroso o gratuito.',
    requisitos: [],
    especiales: ["Ordenanza 1648/98", "Ordenanza 1881/98"],
    links: ["https://hcdvillagesell.com.ar/1648-98-pequenos-hogares-de-tercera-edad/","https://hcdvillagesell.com.ar/1881-02-pequenos-hogares-para-la-tercera-edad-ver-ord-n-1648-98-hogar-geriatrico/"],
    pom: "https://drive.google.com/file/d/1wxs6xEw_L6AFirUATtLgtNheGJCGGcny/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 75,
    nombre: 'Veterinaria',
    descripcion: 'Local destinado a la atención médica de animales domésticos. Pudiendo tener como anexo compatible el uso de venta de accesorios y alimentos para dichos animales con excepción de lavado de mascotas.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1cTwYRlUxrIynPMbCe4yHUzEKJB_ZWfke/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 76,
    nombre: 'Culturales',
    descripcion: 'Establecimientos destinados al fomento y goce del conocimiento y la cultura.',
    requisitos: ["Art.6"],
    especiales: [],
    links: [],
    pom: "",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 77,
    nombre: 'Biblioteca',
    descripcion: 'Establecimiento dedicado al almacenamiento, consulta y difusión de libros, revistas, periódicos, discos, grabaciones, etc.',
    requisitos: ["Art.6"],
    especiales: [],
    links: [],
    pom: "https://drive.google.com/file/d/1v6YfrnquDF2J2uhg6ghbkOXMZt6WOyJy/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 78,
    nombre: 'Museo',
    descripcion: 'Establecimiento donde se coleccionan y exhiben al público elementos históricos, de arte, técnica o ciencia. Constituyendo o no el edificio en sí un bien del patrimonio artístico o histórico.',
    requisitos: ["Art.6"],
    especiales: [],
    links: [],
    pom: "https://drive.google.com/file/d/1LR95z81sliReLhoH8kYYW7kf-MDPAVhc/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 79,
    nombre: 'Cine, Teatro',
    descripcion: 'Establecimiento cerrado donde se proyectan películas y/o se practican obras teatrales. Lugar de reuniones caracterizado por poseer un espacio, que puede albergar espectadores que observan la función, desarrollada en un escenario, tarima, podio, plataforma o elemento similar.',
    requisitos: ["Art.6"],
    especiales: ["Art 9 inc. i", "Certificado Anti siniestral - Ministerio de Seguridad - Bomberos de Costa del Este - Ministerio de Seguridad de la Provincia de Buenos Aires.", "Seguro Responsabilidad Civil."],
    links: [],
    pom: "https://drive.google.com/file/d/1KPN1dwnAj-LSboWLiolO9I8sfMVMUSjV/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 80,
    nombre: 'Centro de Exposiciones, Galería de Arte',
    descripcion: 'Espacio para la exhibición y promoción del arte, en especial del arte visual, y principalmente pintura y escultura, de forma similar a un museo, caracterizado por la alternancia de las obras expuestas en el tiempo.',
    requisitos: ["Art.6"],
    especiales: ["Art 9 inc. i"],
    links: [],
    pom: "https://drive.google.com/file/d/15FWsXAStnA2JQP5i-IL4pdaiRTQM6MU8/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 81,
    nombre: 'Salón de Conferencias',
    descripcion: 'Local donde pueden llevarse a cabo conferencias científicas, empresariales, etc. De morfología y funcionamiento análogo al cine o teatro.',
    requisitos: ["Art.6"],
    especiales: ["Art 9 inc i"],
    links: [],
    pom: "https://drive.google.com/file/d/1fyER3IjMRD4YKgTjCqheo0wsgfZWgeVx/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 82,
    nombre: 'Autocine',
    descripcion: 'Explanada donde se ubican automóviles cuyos ocupantes asisten a la proyección de películas.',
    requisitos: ["Art.6"],
    especiales: ["Art 9 inc. i", "Certificado Anti siniestral - Ministerio de Seguridad - Bomberos de Costa del Este - Ministerio de Seguridad de la Provincia de Buenos Aires.", "Seguro Responsabilidad Civil."],
    links: [],
    pom: "https://drive.google.com/file/d/1wo0lSrWg8cAXgjzqhCx_nmxKRy71vQcH/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 83,
    nombre: 'Acuario',
    descripcion: 'Espacio abierto o cubierto donde se exhiben ambientes subacuáticos de agua dulce, marina o salobre con fines educativos y de conservación.',
    requisitos: ["Art.6"],
    especiales: ["Art 9 inc. i", "Certificado Anti siniestral - Ministerio de Seguridad - Bomberos de Costa del Este - Ministerio de Seguridad de la Provincia de Buenos Aires.", "Seguro Responsabilidad Civil."],
    links: [],
    pom: "https://drive.google.com/file/d/1DmbhlSfdE5UI01cR4k6MJuyOB_LkyETe/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 84,
    nombre: 'Religiosos',
    descripcion: 'Establecimientos destinados a la organización de personas con el propósito de adoración, estudio y difusión teológica. Reuniones de carácter reflexivo, de estímulo espiritual.',
    requisitos: ["Art.6"],
    especiales: [],
    links: [],
    pom: "https://drive.google.com/file/d/1SqW_Mjw0kcaK00RIAe4lbB-WAJ02Ry5o/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 85,
    nombre: 'Circuitos Deportivos, Canchas de Práctica y Ejercicio',
    descripcion: 'Establecimientos de carácter deportivo con extensas superficies descubiertas destinadas a pistas de competición y/o prácticas para destinos varios, atletismo, golf, motociclismo, etc.',
    requisitos: ["Art.6"],
    especiales: ["Debe realizar consulta a deptocomercio@gesell.gob.ar y presentar anteproyecto"],
    links: [],
    pom: "https://drive.google.com/file/d/1ZyKnB2Yrc9sCba-hg1JmgIjPy9lixYBM/preview",
    inspeccion: true,
    croquis: false,
  },  
  {
    id: 86,
    nombre: 'Natatorio',
    descripcion: 'Establecimiento cubierto o descubierto equipado con natatorio para la práctica de la natación.',
    requisitos: ["Art.6"],
    especiales: ["Ordenanza 501/86"],
    links: ["https://hcdvillagesell.com.ar/0501-86-habilitacion-para-natatorios/"],
    pom: "https://drive.google.com/file/d/1ZQGJZOZhp12YDk248YpBHbESswsg-64p/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 87,
    nombre: 'Gimnasio',
    descripcion: 'Establecimiento cerrado para la práctica de ejercicios y/o disciplinas varias, gimnasia, artes marciales, esgrima, o similares.',
    requisitos: ["Art.6"],
    especiales: ["Debe realizar consulta a deptocomercio@gesell.gob.ar"],
    links: [],
    pom: "https://drive.google.com/file/d/1dGPGEFR35RWZsyYekEByaxWciWKHQOP6/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 88,
    nombre: 'Estadio Deportivo Cubierto',
    descripcion: 'Salón cubierto para la práctica de deportes con o sin cancha, con o sin gradas.',
    requisitos: ["Art.6"],
    especiales: ["Debe realizar consulta a deptocomercio@gesell.gob.ar y presentar anteproyecto."],
    links: [],
    pom: "https://drive.google.com/file/d/1dK4DMSZUuyeygkK_By4_B84t5Ax-faNB/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 89,
    nombre: 'Parque Termal',
    descripcion: 'Establecimiento con instalaciones cubiertas y descubiertas con piscinas de variada temperatura de origen termal, con instalaciones complementarias de servicios, salas de masajes, talleres, etc. Puede incluir terapias en base a aguas marinas.',
    requisitos: ["Art.6"],
    especiales: ["Debe realizar consulta a deptocomercio@gesell.gob.ar y presentar anteproyecto"],
    links: [],
    pom: "https://drive.google.com/file/d/1YGH1hgw-fPPIKeXvVfoNx_NykYc7rpot/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 90,
    nombre: 'Ecoparque',
    descripcion: 'Establecimiento con instalaciones cubiertas y descubiertas provistas de atracciones naturales, jaulas y cercos para animales, jardines botánicos, lagunas artificiales, salas complementarias de cuidados y talleres, etc.',
    requisitos: ["Art.6"],
    especiales: ["Debe realizar consulta a deptocomercio@gesell.gob.ar y presentar anteproyecto"],
    links: [],
    pom: "https://drive.google.com/file/d/1YGH1hgw-fPPIKeXvVfoNx_NykYc7rpot/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 91,
    nombre: 'Parque Temático',
    descripcion: 'Establecimiento con instalaciones cubiertas y descubiertas provistas de atracciones mecánica y electromecánicas de carácter lúdico, con focalización temática en esa oferta de servicios.',
    requisitos: ["Art.6"],
    especiales: ["Debe realizar consulta a deptocomercio@gesell.gob.ar y presentar anteproyecto"],
    links: [],
    pom: "https://drive.google.com/file/d/1YGH1hgw-fPPIKeXvVfoNx_NykYc7rpot/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 92,
    nombre: 'Parque Acuático',
    descripcion: 'Establecimiento con instalaciones cubiertas y descubiertas afectadas a actividades náuticas de baja escala, baños y juegos en base a agua.',
    requisitos: ["Art.6"],
    especiales: ["Debe realizar consulta a deptocomercio@gesell.gob.ar y presentar anteproyecto"],
    links: [],
    pom: "https://drive.google.com/file/d/1YGH1hgw-fPPIKeXvVfoNx_NykYc7rpot/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 93,
    nombre: 'Servicios Administrativos',
    descripcion: 'Comprende sedes de administración pública, organismos y/o entidades públicas o privadas destinadas a la prestación de servicios públicos, bancarios o financieros, compañías de seguros, agencias de cambio, etc. así como oficinas en general, estudios profesionales, agencias de viajes y turismo, inmobiliarias, etc.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f", "Agencias de Viajes y Turismo: Acreditar la Habilitación otorgada por el Ministerio de Turismo y Deportes de la Nación"],
    links: [],
    pom: "",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 94,
    nombre: 'Oficina Pública con o sin Acceso de Público',
    descripcion: 'Local o edificio de la administración pública nacional, provincial, municipal, incluyendo entidades descentralizadas, empresas o sociedades del Estado, en el cual se efectúan tareas técnicas administrativas, productivas o científicas. Suponen afluencia de público. Incluye depósito y corralones dependientes de la administración pública.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1qKg8Yc50Agl4VhMna8w5QmJB-Bk8ylgc/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 95,
    nombre: 'Oficina Consultora',
    descripcion: 'Uno o más locales en los cuales se desarrolla un servicio profesional prestado por empresas o profesionales en forma individual con experiencia o conocimiento específico en un área, asesorando personas, empresas, grupos de empresas, países u organizaciones en general.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1igSbbnK8qwh0LaoT_V0kmp9H7GFg3T5z/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 96,
    nombre: 'Oficina Postal, Cobro de Impuestos y Servicios',
    descripcion: 'Establecimientos postales y/o autorizados para el cobro de impuestos o servicios.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/1igSbbnK8qwh0LaoT_V0kmp9H7GFg3T5z/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 97,
    nombre: 'Oficina Comercial de Servicios',
    descripcion: 'Establecimientos que administran servicios públicos. Incluyen áreas de atención al público consumidor usuario, así como a los galpones destinados al equipamiento y servicio.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/15roVzfNTyih5pRQb7OS5oP6gDhGA5Rn6/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 98,
    nombre: 'Agencia de Información y Noticias',
    descripcion: 'Local donde se recogen noticias y se transmiten a la central desde donde, después de tratarla, se envía (radio, diario, revista, etc.)',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc d, y f"],
    links: [],
    pom: "https://drive.google.com/file/d/120LfzO3BXcx67SM91I3e9yNIbZRq0VHa/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 99,
    nombre: 'Agencias Comerciales y Turismo',
    descripcion: 'Local donde se desarrolla una actividad comercial delegada a un intermediario. El local no incluye depósito ni expende mercaderías.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc d, y f (Ord. 1958/04)", "Ordenanza 858/90", "Ordenanza 1640/98", "Agencias de Viajes y Turismo: Acreditar la Habilitación otorgada por el Ministerio de Turismo y Deportes de la Nación"],
    links: ["","https://hcdvillagesell.com.ar/0858-90-reglamentacion-de-empresas-de-excursion-en-villa-gesell/","https://hcdvillagesell.com.ar/1640-98-modifica-ord-0858-90-reglamento-de-excursiones/"],
    pom: "https://drive.google.com/file/d/120LfzO3BXcx67SM91I3e9yNIbZRq0VHa/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 100,
    nombre: 'Restaurante',
    descripcion: 'Establecimientos destinados al servicio de platos fríos o calientes en salón comedor propio, elaborados de variada composición, en una cocina ubicada en el mismo lugar, en sus diferentes variantes y menús: Restaurantes, parrillas, pizzerías, pescados, pastas, hamburgueserías, etc.). Anexo Compatible: Pizzería, Comidas para llevar',
    requisitos: ["Art.6"],
    especiales: ["Art. 7 inc. a, b, c, e, f, y h", 
    "Croquis de Instalaciones visado por profesional habilitante, escala 1:50 con el siguiente detalle: a) Planta del local con medidas, ubicación de mesadas, tirajes, fogones, cocinas, freidoras, aberturas, paredes internas, y ventilaciones, depósitos, baños, salón de venta y/o consumición, vestuarios, entrepisos, ubicación de garrafas, etc; b) Detalle en corte transversal piso, cielorraso, alturas de tirajes con indicación de altura a 4 vientos; c) Marcar ubicación del matafuegos, clase y kg."],
    links: [],
    pom: "https://drive.google.com/file/d/1N0XSQ_OxmNYzLv7yMNu06Q63hOsy-EuF/preview",
    inspeccion: true,
    croquis: true,
  },
  {
    id: 101,
    nombre: 'Panchería / Hamburguesería',
    descripcion: 'Establecimientos dedicados al servicio de un plato único o de un menú muy acotado, para servicio en salón propio y/o al paso.',
    requisitos: ["Art.6"],
    especiales: ["Ordenanza 2280/09",
    "Croquis de Instalaciones visado por profesional habilitante, escala 1:50 con el siguiente detalle: a) Planta del local con medidas, ubicación de mesadas, tirajes, fogones, cocinas, freidoras, aberturas, paredes internas, y ventilaciones, depósitos, baños, salón de venta y/o consumición, vestuarios, entrepisos, ubicación de garrafas, etc; b) Detalle en corte transversal piso, cielorraso, alturas de tirajes con indicación de altura a 4 vientos; c) Marcar ubicación del matafuegos, clase y kg."],
    links: ["https://hcdvillagesell.com.ar/2280-09-habilitacion-de-comercio-de-ventas-de-panchos/"],
    pom: "https://drive.google.com/file/d/12VaxtN0lNUadfewGQt0vc7VQKCALh4r3/preview",
    inspeccion: true,
    croquis: true,
  },
  {
    id: 102,
    nombre: 'Cafetería / Bar',
    descripcion: 'Establecimiento donde se sirven aperitivos y comidas, generalmente platos combinados, pero no menúes o cartas. Incluye expendio de bebidas alcohólicas para consumo en el lugar. Anexo Compatible Pastelería.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. a, b, c, e y f",     
    "Croquis de Instalaciones visado por profesional habilitante, escala 1:50 con el siguiente detalle: a) Planta del local con medidas, ubicación de mesadas, tirajes, fogones, cocinas, freidoras, aberturas, paredes internas, y ventilaciones, depósitos, baños, salón de venta y/o consumición, vestuarios, entrepisos, ubicación de garrafas, etc; b) Detalle en corte transversal piso, cielorraso, alturas de tirajes con indicación de altura a 4 vientos; c) Marcar ubicación del matafuegos, clase y kg."],
    links: [],
    pom: "https://drive.google.com/file/d/1LK3ZirzC1n6wFdEWvtX97WY_KkCW0Go0/preview",
    inspeccion: true,
    croquis: true,
  },
  {
    id: 103,
    nombre: 'Café-Concert',
    descripcion: 'Local donde además de una consumición (bebida y comida) el público presencia espectáculos musicales, teatrales o mixtos.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. a, b, c, e y f", 
    "Croquis de Instalaciones visado por profesional habilitante, escala 1:50 con el siguiente detalle: a) Planta del local con medidas, ubicación de mesadas, tirajes, fogones, cocinas, freidoras, aberturas, paredes internas, y ventilaciones, depósitos, baños, salón de venta y/o consumición, vestuarios, entrepisos, ubicación de garrafas, etc; b) Detalle en corte transversal piso, cielorraso, alturas de tirajes con indicación de altura a 4 vientos; c) Marcar ubicación del matafuegos, clase y kg.",
    "Certificado Anti siniestral - Ministerio de Seguridad - Bomberos de Costa del Este - Ministerio de Seguridad de la Provincia de Buenos Aires.", "Seguro Responsabilidad Civil y otros."],
    links: [],
    pom: "https://drive.google.com/file/d/1AcllX5Wjbq-PzjuCYQIGVF9Gyh0A5QIa/preview",
    inspeccion: true,
    croquis: true,
  },
  {
    id: 104,
    nombre: 'Discoteca',
    descripcion: 'Local público por el cual, a cambio de un pago de acceso, con horario regularmente nocturno, se escucha música grabada o en vivo, baila y/o se interactúa con otras personas y se consumen bebidas.',
    requisitos: ["Art.6"],
    especiales: ["Art 3 bis inc. b", "Certificado Anti siniestral - Ministerio de Seguridad - Bomberos de Costa del Este - Ministerio de Seguridad de la Provincia de Buenos Aires.", "Seguro Responsabilidad Civil y otros (consultar a deptocomercio@gesell.gob.ar)."],
    links: [],
    pom: "https://drive.google.com/file/d/1sqU9mLaF-KTi72KXZUx8tOA1h2VF3SEK/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 105,
    nombre: 'Fúnebres',
    descripcion: 'Comprende establecimientos destinados al funcionamiento de servicios funerarios, casas velatorias y actividades relacionadas.',
    requisitos: ["Art.6"],
    especiales: ["Art 9 inc. ll"],
    links: [],
    pom: "https://drive.google.com/file/d/1winhWzgPTXr85gkxA9OTyHYpSPIgNWuX/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 106,
    nombre: 'Seguridad',
    descripcion: 'Comprende actividades destinadas a la defensa y seguridad del Estado y protección a ciudadanos y bienes. Incluye comisarías, destacamentos y otras dependencias policiales, cuarteles de bomberos o defensa civil.',
    requisitos: ["Art.6", "Consultar a deptocomercio@gesell.gob.ar"],
    especiales: [],
    links: [],
    pom: "",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 107,
    nombre: 'Servicios del Automotor y Náutica',
    descripcion: 'Comprende actividades destinadas al mantenimiento, reparación y atención del parque automotor y náutico público y privado, incluyendo talleres mecánicos y lavaderos.',
    requisitos: ["Art.6"],
    especiales: ["Art 9 inc. c, e y l"],
    links: [],
    pom: "",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 108,
    nombre: 'Gomería',
    descripcion: 'Local donde se realizan reparaciones sencillas, básicamente de neumáticos, donde los vehículos no quedan en depósito en el lugar.',
    requisitos: ["Art.6"],
    especiales: ["Art 9 inc. c"],
    links: [],
    pom: "https://drive.google.com/file/d/1bOpcWvrTESWdNYAlv8ew_LmtrxTWh79F/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 109,
    nombre: 'Taller de Chapa y Pinturas',
    descripcion: 'Establecimientos afectados a las tareas de reparación de carrocerías y repintado.',
    requisitos: ["Art.6"],
    especiales: ["Art 9 inc. c"],
    links: [],
    pom: "https://drive.google.com/file/d/1bOpcWvrTESWdNYAlv8ew_LmtrxTWh79F/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 110,
    nombre: 'Taller de Mecánica',
    descripcion: 'Establecimiento dedicado a la reparación de la mecánica automotor.',
    requisitos: ["Art.6"],
    especiales: ["Art 9 inc. c"],
    links: [],
    pom: "https://drive.google.com/file/d/19Ebpi1j4E8WcT98y3PyxofgM3ns9DKHO/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 111,
    nombre: 'Lavadero Automático o Semiautomático de Automóviles',
    descripcion: 'Establecimientos dedicados al lavado y/o aspirado de carrocería e interiores.',
    requisitos: ["Art.6"],
    especiales: ["Art 9 inc. e"],
    links: [],
    pom: "https://drive.google.com/file/d/19Ebpi1j4E8WcT98y3PyxofgM3ns9DKHO/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 112,
    nombre: 'Garaje',
    descripcion: 'Edificio o parte de él destinado a la guarda de vehículos automotores.',
    requisitos: ["Art.6"],
    especiales: ["Art 9 inc. b"],
    links: [],
    pom: "https://drive.google.com/file/d/19NXNZosDrTDHN5pAvTmoBjCK6Ki2z3yr/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 113,
    nombre: 'Playa de Estacionamiento',
    descripcion: 'Parcela urbana o parte de ella afectada a la guarda de vehículos automotores.',
    requisitos: ["Art.6"],
    especiales: ["Art 9 inc. j"],
    links: [],
    pom: "https://drive.google.com/file/d/12kL6AUMfX_WrFu5CI0dU6A8nRbZqJ0li/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 114,
    nombre: 'Estación de Servicio',
    descripcion: 'Establecimiento donde se expenden combustibles (nafta, gasoil, GNC) y aditivos para el automotor mediante surtidos emplazados en playa de maniobra. Anexo Compatible: Autoservicio incorporado a Estaciones de Servicios.',
    requisitos: ["Art.6"],
    especiales: ["Art 8 inc. 26 (Ord. 1958/04)", "Ordenanza 1218/94", "Resolución 25/00 (Presentar Certificado de Instalaciones SASH (Líquidos GNC Duales). Secretaría de Energía","Deberán verificar distancia mínima a cualquier establecimiento educativo de 100 ms."],
    links: ["","https://hcdvillagesell.com.ar/1218-94-autoservicios-en-estacion-de-servicios/","http://mepriv.mecon.gov.ar/Normas/25-00.htm"],
    pom: "https://drive.google.com/file/d/1m5v8nrE_EHhYMJIvpDuNW2TqoAcfY6FS/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 115,
    nombre: 'Transporte',
    descripcion: 'Establecimientos afectados al transporte público de personas y/o mercaderías. Comprende playas de maniobra, estacionamientos, atención y depósito, salas de espera y embarque.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultar a deptocomercio@gesell.gob.ar", "Los vehículos afectados a la actividad comercial deben habilitarse en la dirección de tránsito de la municipalidad de Villa Gesell y renovarse según normativa vigente."],
    links: [],
    pom: "",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 116,
    nombre: 'Expreso de Carga Liviana (Taxi Flet)',
    descripcion: 'Local donde se prestan servicios de transporte de carga liviana, que incluye paquetería y encomienda.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultar a deptocomercio@gesell.gob.ar"],
    links: [],
    pom: "https://drive.google.com/file/d/1RF08MlOCSOrAizF5bIh_OLscT2b4B_0E/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 117,
    nombre: 'Expreso de Cargas Generales',
    descripcion: 'Servicio afectado al transporte de productos de gran porte, por lo general interjurisdiccional, con depósito.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultar a deptocomercio@gesell.gob.ar"],
    links: [],
    pom: "https://drive.google.com/file/d/1bOpcWvrTESWdNYAlv8ew_LmtrxTWh79F/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 118,
    nombre: 'Agencia de Taxi y/o Remise',
    descripcion: 'Local destinado a la atención al público y recepción de pedidos de servicios referidos al transporte de personas a pedido con destino no preestablecido.',
    requisitos: ["Art.6"],
    especiales: ["Ordenanza N.º 1867/02"],
    links: ["https://hcdvillagesell.com.ar/ordenanza-1867-02/"],
    pom: "https://drive.google.com/file/d/1ZSIdt3vVw7ce4hcpJmvu98w6Xtzbb2cy/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 119,
    nombre: 'Salida de Excursiones',
    descripcion: 'Actividad referida al transporte con destino específico pre pautado de carácter turístico.',
    requisitos: ["Art.6"],
    especiales: ["Art 7 inc. d, y f (Ord. 1958/04)", "Ordenanza 858/90", "Ordenanza 1640/98", "Agencias de Viajes y Turismo: Acreditar la Habilitación otorgada por el Ministerio de Turismo y Deportes de la Nación"],
    links: ["","https://hcdvillagesell.com.ar/0858-90-reglamentacion-de-empresas-de-excursion-en-villa-gesell/","https://hcdvillagesell.com.ar/1640-98-modifica-ord-0858-90-reglamento-de-excursiones/"],
    pom: "https://drive.google.com/file/d/1kclCKMDzoeQ8RicA28BKUzZdzy6z_w7R/preview",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 120,
    nombre: 'Terminal de Ómnibus',
    descripcion: 'Establecimientos afectados al transporte de personas dentro y fuera de la jurisdicción. Serán de corta, media y/o larga distancia.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultar a deptocomercio@gesell.gob.ar"],
    links: [],
    pom: "https://drive.google.com/file/d/1FR4w8FlBjZsF8dFAreC4_XcO9Eyvhkdo/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 121,
    nombre: 'Centro de Concentración Logística',
    descripcion: 'Predios donde se brinden servicios de alquiler y uso de espacios para: carga, descarga, distribución, redistribución y almacenamiento de mercadería transportada.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultar a deptocomercio@gesell.gob.ar y presentar anteproyecto."],
    links: [],
    pom: "https://drive.google.com/file/d/1bOpcWvrTESWdNYAlv8ew_LmtrxTWh79F/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 122,
    nombre: 'Infraestructuras',
    descripcion: 'Comprende instalaciones relacionadas a sistemas, producción, almacenamiento, tratamiento o distribución de fluidos y energía, de comunicación y de tratamiento de residuos.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultar a deptocomercio@gesell.gob.ar y presentar anteproyecto."],
    links: [],
    pom: "",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 123,
    nombre: 'Planta de Tratamiento de RSU',
    descripcion: 'Establecimientos afectados a procesos relacionados con la gestión de residuos sólidos urbanos (RSU), clasificación, almacenamiento y transporte posterior a sitio de disposición final y/o de recuperación y reconversión.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultar a deptocomercio@gesell.gob.ar y presentar anteproyecto."],
    links: [],
    pom: "https://drive.google.com/file/d/1U3iOzvCPYm_JhPePpv7YFd0m7c9HlpCp/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 124,
    nombre: 'Punto Limpio',
    descripcion: 'Establecimiento para el acopio temporal de residuos de la poda y/o el movimiento de suelos previo posterior tratamiento y/o destino final.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultar a deptocomercio@gesell.gob.ar y presentar anteproyecto."],
    links: [],
    pom: "https://drive.google.com/file/d/1GJnxFtBPIfjoJcTk8xzjzmpFxTephmvX/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 125,
    nombre: 'Planta de Tratamiento de Efluentes Cloacales',
    descripcion: 'Establecimiento para el final y saneamiento de efluentes cloacales para su vuelco final posterior.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultar a deptocomercio@gesell.gob.ar y presentar anteproyecto."],
    links: [],
    pom: "https://drive.google.com/file/d/1U3iOzvCPYm_JhPePpv7YFd0m7c9HlpCp/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 126,
    nombre: 'Planta Productora y Transmisora de Radio y TV',
    descripcion: 'Establecimiento productor de contenidos con instalación de antenas, estudios, depósitos y oficinas comerciales.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultar a deptocomercio@gesell.gob.ar y presentar anteproyecto."],
    links: [],
    pom: "https://drive.google.com/file/d/1bOpcWvrTESWdNYAlv8ew_LmtrxTWh79F/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 127,
    nombre: 'Establecimientos Ictícolas',
    descripcion: 'Cría y procesamiento de pescados de agua dulce.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultar a deptocomercio@gesell.gob.ar y presentar anteproyecto."],
    links: [],
    pom: "https://drive.google.com/file/d/1U3iOzvCPYm_JhPePpv7YFd0m7c9HlpCp/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 128,
    nombre: 'Huertas',
    descripcion: 'Siembra y cosecha de verduras, legumbres y hortalizas, así como frutales.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultar a deptocomercio@gesell.gob.ar y presentar anteproyecto."],
    links: [],
    pom: "https://drive.google.com/file/d/1U3iOzvCPYm_JhPePpv7YFd0m7c9HlpCp/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 129,
    nombre: 'Establecimientos Apícolas',
    descripcion: 'Cosecha, tratamiento y fraccionamiento de miel.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultar a deptocomercio@gesell.gob.ar y presentar anteproyecto."],
    links: [],
    pom: "https://drive.google.com/file/d/1U3iOzvCPYm_JhPePpv7YFd0m7c9HlpCp/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 130,
    nombre: 'Granjas Avícolas y/o Cunícolas',
    descripcion: 'Cría y faena de aves de corral y conejos.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultar a deptocomercio@gesell.gob.ar y presentar anteproyecto."],
    links: [],
    pom: "https://drive.google.com/file/d/1U3iOzvCPYm_JhPePpv7YFd0m7c9HlpCp/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 131,
    nombre: 'Equipamiento Social, Recreativo y/o Deportivo',
    descripcion: 'Equipamientos destinados al encuentro social y/o deportivo, así como a la práctica, enseñanza o exhibición de deportes con o sin asistencia de espectadores. Incluye clubes, sociedades de fomento, agrupaciones tradicionalistas, así como asociaciones y centros recreativos de entidades públicas y privadas, gimnasios, piscinas y canchas de tenis, padel, básquet, vóley.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultar a deptocomercio@gesell.gob.ar y presentar anteproyecto"],
    links: [],
    pom: "",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 132,
    nombre: 'Club de Barrio',
    descripcion: 'Establecimiento de alcance y complejidad barrial destinado al encuentro social, deportivo y lúdico.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultar a deptocomercio@gesell.gob.ar y presentar anteproyecto"],
    links: [],
    pom: "https://drive.google.com/file/d/1Xea88cjjPOUldVq4wSCqbWOTuY8Pn9O6/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 133,
    nombre: 'Peña',
    descripcion: 'Espacio mixto, socio-cultural y comercial, donde se desarrollan actividades artísticas y/o lúdicas como canto, narración oral, pintura, telar, plástica, aprendizaje y práctica de danzas típicas argentinas expresadas por artistas propios o concurrentes, teatro criollo, títeres, donde se elaboran y/o expenden comidas y bebidas típicas regionales del país.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultar a deptocomercio@gesell.gob.ar y presentar anteproyecto"],
    links: [],
    pom: "https://drive.google.com/file/d/16dXPQ4J2HjWxm6gHQnM-JSt0WP1RE-8y/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 135,
    nombre: 'Salón de Fiesta o Diversión',
    descripcion: 'Establecimiento destinado a la realización de eventos, recreación, cumpleaños, casamientos, ocio, relación social y actividades asociadas con asistencia de espectadores, donde en general no se cobra un derecho de acceso y el evento resulta programado con anticipación y sin regularidad horaria y/o diaria.',
    requisitos: ["Art.6"],
    especiales: ["Deberá consultar a deptocomercio@gesell.gob.ar"],
    links: [],
    pom: "https://drive.google.com/file/d/1BhZDomy1LTk4qY3Tys88fcOeoH23BaiL/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 136,
    nombre: 'Hotel',
    descripcion: 'Alojamiento Turístico Hotelero que presta al turista, mediante contrato de hospedaje los servicios de gastronomía, recepción, portería, personal, sin perjuicio de los demás que para cada categoría expresamente se indican.',
    requisitos: [],
    especiales: ["Ley 14209 - Provincia de Buenos Aires", "Decreto 13/14 - Provincia de Buenos Aires"],
    links: ["https://normas.gba.gob.ar/ar-b/ley/2010/14209/11570","https://normas.gba.gob.ar/ar-b/decreto/2014/13/172740"],
    pom: "https://drive.google.com/file/d/1u2NBR8pvj13c-gTmDNOvnJqray7aaoTd/preview",
    inspeccion: true,
    croquis: true,
    croquisExpandido: true,
  },
  {
    id: 137,
    nombre: 'Apart-Hotel',
    descripcion: 'Alojamiento Turístico Hotelero que presta al turista el servicio de alojamiento en edificios de departamentos que integran una unidad con administración común, ofreciendo además los servicios propios del hotel.',
    requisitos: [],
    especiales: ["Ley 14209 - Provincia de Buenos Aires", "Decreto 13/14 - Provincia de Buenos Aires"],
    links: ["https://normas.gba.gob.ar/ar-b/ley/2010/14209/11570","https://normas.gba.gob.ar/ar-b/decreto/2014/13/172740"],
    pom: "https://drive.google.com/file/d/1aNtN0OqUsm-867qijNEsCb-zbg16KAmH/preview",
    inspeccion: true,
    croquis: true,
    croquisExpandido: true,
  },
  {
    id: 138,
    nombre: 'Hotel Boutique',
    descripcion: 'Alojamiento Turístico Hotelero caracterizado y distinguido por su atención personalizada, peculiaridad en sus instalaciones o en sus prestaciones de servicios, originalidad y estilo, destacándose por el valor artístico del inmueble, diseño, ambientación o decoración, pudiendo algunos ser temáticos.',
    requisitos: [],
    especiales: ["Ley 14209 - Provincia de Buenos Aires", "Decreto 13/14 - Provincia de Buenos Aires"],
    links: ["https://normas.gba.gob.ar/ar-b/ley/2010/14209/11570","https://normas.gba.gob.ar/ar-b/decreto/2014/13/172740"],
    pom: "https://drive.google.com/file/d/1NvvSakBQa2Evx_C3EDmOI3b_AjM4r6VZ/preview",
    inspeccion: true,
    croquis: true,
    croquisExpandido: true,
  },
  {
    id: 139,
    nombre: 'Hostería',
    descripcion: 'Alojamiento Turístico Hotelero que reúne características de diseño arquitectónico acorde al medio natural y/o urbano en el que se encuentra situado.',
    requisitos: [],
    especiales: ["Ley 14209 - Provincia de Buenos Aires", "Decreto 13/14 - Provincia de Buenos Aires"],
    links: ["https://normas.gba.gob.ar/ar-b/ley/2010/14209/11570","https://normas.gba.gob.ar/ar-b/decreto/2014/13/172740"],
    pom: "https://drive.google.com/file/d/1T7piT8VYks0YIP7x_PJxZW50blUbsVj5/preview",
    inspeccion: true,
    croquis: true,
    croquisExpandido: true,
  },
  {
    id: 140,
    nombre: 'Residencial',
    descripcion: 'Alojamiento Turístico Hotelero que presta al turista servicios semejantes al hotel, y que por sus características no posee las instalaciones y servicios necesarios para ser considerado como Hotel en su categoría mínima.',
    requisitos: [],
    especiales: ["Ley 14209 - Provincia de Buenos Aires", "Decreto 13/14 - Provincia de Buenos Aires"],
    links: ["https://normas.gba.gob.ar/ar-b/ley/2010/14209/11570","https://normas.gba.gob.ar/ar-b/decreto/2014/13/172740"],
    pom: "https://drive.google.com/file/d/1nD4hGPMJkcHvl8mmzMIV2yCCZcFiCK9-/preview",
    inspeccion: true,
    croquis: true,
    croquisExpandido: true,
  },
  {
    id: 141,
    nombre: 'Hostel',
    descripcion: 'Alojamiento Turístico Hotelero en el que se brinda alojamiento en habitaciones compartidas pudiendo contar con habitaciones privadas, con baños compartidos y/o privados, con espacios comunes de estar, comedor y cocina equipada para que los huéspedes preparen sus alimentos facilitando así la integración sociocultural entre ellos, sin perjuicio de contar con otros servicios complementarios.',
    requisitos: [],
    especiales: ["Ley 14209 - Provincia de Buenos Aires", "Decreto 13/14 - Provincia de Buenos Aires"],
    links: ["https://normas.gba.gob.ar/ar-b/ley/2010/14209/11570","https://normas.gba.gob.ar/ar-b/decreto/2014/13/172740"],
    pom: "https://drive.google.com/file/d/1x2LbroXbacldpO1bqgB1RSZ_ySRBLJkw/preview",
    inspeccion: true,
    croquis: true,
    croquisExpandido: true,
  },
  {
    id: 142,
    nombre: 'Albergue Juvenil',
    descripcion: 'Se entiende como tal a aquel establecimiento en el que se preste el servicio de alojamiento colectivo pudiendo estar conformado por pabellones comunes separados por sexo. Cada pabellón podrá disponer de una capacidad máxima de 20 (veinte) plazas o por habitaciones de 1 a 6 plazas, con baños privados.',
    requisitos: [],
    especiales: ["Ley 14209 - Provincia de Buenos Aires", "Decreto 13/14 - Provincia de Buenos Aires"],
    links: ["https://normas.gba.gob.ar/ar-b/ley/2010/14209/11570","https://normas.gba.gob.ar/ar-b/decreto/2014/13/172740"],
    pom: "https://drive.google.com/file/d/1eQjKPl7Qwop8gk5d8AHbv5YBcIegC1HI/preview",
    inspeccion: true,
    croquis: true,
    croquisExpandido: true,
  },
  {
    id: 143,
    nombre: 'Cama y Desayuno (Bed & Breakfast)',
    descripcion: 'Alojamiento Turístico Hotelero que ocupa la totalidad o parte independizada de un inmueble con una unidad de explotación, en el que sus propietarios brindan un servicio personalizado de tipo artesanal de cama y desayuno.',
    requisitos: [],
    especiales: ["Ley 14209 - Provincia de Buenos Aires", "Decreto 13/14 - Provincia de Buenos Aires"],
    links: ["https://normas.gba.gob.ar/ar-b/ley/2010/14209/11570","https://normas.gba.gob.ar/ar-b/decreto/2014/13/172740"],
    pom: "https://drive.google.com/file/d/12nSP2WqDb9fRqy5fOtKm3kres8-kEtOu/preview",
    inspeccion: true,
    croquis: true,
    croquisExpandido: true,
  },
  {
    id: 144,
    nombre: 'Cabaña',
    descripcion: 'Alojamiento Turístico Hotelero compuesto por unidades independientes que aisladamente o formando un conjunto con otras se integran a una unidad de administración común, situadas generalmente fuera del radio céntrico, en el que se presta al turismo el servicio de alojamiento, sin perjuicio de los demás servicios complementarios que para cada categoría se exige.',
    requisitos: [],
    especiales: ["Ley 14209 - Provincia de Buenos Aires", "Decreto 13/14 - Provincia de Buenos Aires"],
    links: ["https://normas.gba.gob.ar/ar-b/ley/2010/14209/11570","https://normas.gba.gob.ar/ar-b/decreto/2014/13/172740"],
    pom: "https://drive.google.com/file/d/12nSP2WqDb9fRqy5fOtKm3kres8-kEtOu/preview",
    inspeccion: true,
    croquis: true,
    croquisExpandido: true,
  },
  {
    id: 145,
    nombre: 'Casa o Departamento con Servicios',
    descripcion: 'Alojamiento Turístico Hotelero compuesto por unidades habitacionales amobladas que, ubicadas en forma individual, en edificios o conjuntos de viviendas, brinden servicios complementarios al de alojamiento de manera habitual y se arrienden por un periodo que no supere las ciento ochenta (180) pernoctaciones.',
    requisitos: [],
    especiales: ["Ley 14209 - Provincia de Buenos Aires", "Decreto 13/14 - Provincia de Buenos Aires"],
    links: ["https://normas.gba.gob.ar/ar-b/ley/2010/14209/11570","https://normas.gba.gob.ar/ar-b/decreto/2014/13/172740"],
    pom: "https://drive.google.com/file/d/1L4L0vFkBMjdhq-gVlWzAVm4HtCodHxWM/preview",
    inspeccion: true,
    croquis: true,
    croquisExpandido: true,
  },
  {
    id: 146,
    nombre: 'Jumping y Camas Elásticas',
    descripcion: 'Juegos al aire libre.',
    requisitos: ["Art. 6"],
    especiales: ["Art. 3 bis inc. a"],
    links: [],
    pom: "",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 147,
    nombre: 'Glamping',
    descripcion: 'Hospedaje que une el acampe en la naturaleza con el lujo y la comodidad de un hotel de alta gama.',
    requisitos: [],
    especiales: ["Ordenanza 3297/22"],
    links: ["https://hcdvillagesell.com.ar/3297-22-glamping-alojamiento/"],
    pom: "",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 148,
    nombre: 'Elaboración y Venta de Churros',
    descripcion: 'Podrán expender además de los productos mencionados como anexo los siguientes usos compatibles: galletitas, pan y repostería.',
    requisitos: ["Art. 6"],
    especiales: ["Venta: Art. 7 inc. d y f", "Elaboración y Venta: Art. 7 inc. b, d y f", 
    "Croquis de Instalaciones visado por profesional habilitante, escala 1:50 con el siguiente detalle: a) Planta del local con medidas, ubicación de mesadas, tirajes, fogones, cocinas, freidoras, aberturas, paredes internas, y ventilaciones, depósitos, baños, salón de venta y/o consumición, vestuarios, entrepisos, ubicación de garrafas, etc; b) Detalle en corte transversal piso, cielorraso, alturas de tirajes con indicación de altura a 4 vientos; c) Marcar ubicación los matafuegos, clase y kg."],
    links: [],
    pom: "",
    inspeccion: true,
    croquis: true,
  },
  {
    id: 149,
    nombre: 'Elaboración y Venta de Pastas Frescas',
    descripcion: 'Podrán vender pastas secas en envase original y productos alimenticios enlatados.',
    requisitos: ["Art. 6"],
    especiales: ["Venta: Art. 7 inc. d y f", "Elaboración y Venta: Art. 7 inc. b, d y f", 
    "Croquis de Instalaciones visado por profesional habilitante, escala 1:50 con el siguiente detalle: a) Planta del local con medidas, ubicación de mesadas, tirajes, fogones, cocinas, freidoras, aberturas, paredes internas, y ventilaciones, depósitos, baños, salón de venta y/o consumición, vestuarios, entrepisos, ubicación de garrafas, etc; b) Detalle en corte transversal piso, cielorraso, alturas de tirajes con indicación de altura a 4 vientos; c) Marcar ubicación los matafuegos, clase y kg."],
    links: [],
    pom: "",
    inspeccion: true,
    croquis: true,
  },
  {
    id: 150,
    nombre: 'Carpintería',
    descripcion: '',
    requisitos: ["Art. 6"],
    especiales: ["Art. 9 inc. d","Los vehículos afectados a la actividad comercial deben habilitarse en la dirección de tránsito de la municipalidad de Villa Gesell y renovarse según normativa vigente."],
    links: [],
    pom: "https://drive.google.com/file/d/1944-72OJ2xUnQRNS3POH1kjKyvoIQJ6Y/preview",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 151,
    nombre: 'Casa de Té',
    descripcion: 'Podrán expender tés especiales y acompañarlo de pastelería/tortas/etc.',
    requisitos: ["Art. 6"],
    especiales: ["Solo venta: Art. 7 inc. d, y f", "Consumición en el lugar: Art. 7 inc. a, c, d, f y h "],
    links: [],
    pom: "",
    inspeccion: true,
    croquis: false,
  },
  {
    id: 152,
    nombre: 'Oficina de Control de Plagas',
    descripcion: 'Establecimiento cuyo objetivo principal es prevenir el ingreso de plagas en lugares cerrados y/o abiertos según el caso.',
    requisitos: ["Art.6"],
    especiales: ["Ordenanza 2155/08", "Ordenanza 2428/11"],
    links: ["https://hcdvillagesell.com.ar/2155-08-control-de-plagas-comercios/","https://hcdvillagesell.com.ar/ord-2428-11/"],
    pom: "",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 153,
    nombre: 'Oficina de Mensajería',
    descripcion: 'Servicio de transporte y reparto de cartas y paquetes, generalmente dentro de una misma población.',
    requisitos: ["Art.6"],
    especiales: ["Ordenanza 1974/04"],
    links: ["https://hcdvillagesell.com.ar/1974-04-servicio-de-mensajeria/"],
    pom: "",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 154,
    nombre: 'Tatuajes',
    descripcion: 'Establecimiento donde se altera de manera temporal o permanente el color de la piel, sobre la cual se plasma un dibujo, un patrón, una figura o un texto, efectuado con agujas u otros utensilios que inyectan tinta o algún otro pigmento en la dermis de una persona.',
    requisitos: ["Art.6"],
    especiales: ["Ordenanza 1985/04"],
    links: ["https://hcdvillagesell.com.ar/1985-04-tatuajes-piercing/"],
    pom: "",
    inspeccion: false,
    croquis: false,
  },
  {
    id: 155,
    nombre: 'Escuela de Surf, Bodyboard y Kitesurf',
    descripcion: '',
    requisitos: [],
    especiales: ["Deberá solicitar autorización previa de la Dirección de Seguridad en Playa", "Deberá realizar consulta en deptocomercio@gesell.gob.ar"],
    links: [],
    pom: "",
    inspeccion: true,
    croquis: false,
  }
  ];
  
  export default rubros;